name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - source # branch name

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}